### PR TITLE
updated readme: added install instructions + badges

### PR DESCRIPTION
**Pull request by sugatoray**
Only README file has been updated. Closes #673.

- Added badges: 
  - [x] license 
  - [x] pypi 
  - [x] conda

- Added installation instructions: 
  - [x] pip 
  - [x] conda

### CODE REVIEW

**Comment by sugatoray** [comment]
@brunobord Please take a look at this. Hopefully this is straight forward enough for merging. In case, you think there should be some changes, please let me know. Thank you.

**Review by brunobord — CHANGES_REQUESTED** [review]
looks awesome. could you please add a small item to the Changelog? I'll merge this right away.

**Comment by sugatoray** [comment]
> looks awesome. could you please add a small item to the Changelog? I'll merge this right away.

@brunobord Sure, I will add it to the changelog. Thank you.

**Comment by sugatoray** [comment]
@brunobord Just updated the changelog.

**Pull request merged**
