### PR TITLE
Add calendar for Georgia (country)

### PR DESCRIPTION
**Pull request by atj01**
This PR is intended to add a new calendar for the country of Georgia. 

For information, read and make sure you're okay with the [Contributing guidelines](https://workalendar.github.io/workalendar/contributing.html#adding-new-calendars).

- [x] Tests with a significant number of years to be tested for your calendar.
- [x] Docstrings for the Calendar class and specific methods.
- [x] Use the ``workalendar.registry_tools.iso_register`` decorator to register your new calendar using ISO codes (optional).
- [x] Calendar country / label added to the README.md file.
- [x] Changelog amended with a mention like: "Added ``<country>`` by ``@pseudo`` (#)". **Note** *Please do NOT change the version number here. It's the project maintainers' duty.*

### CODE REVIEW

**Comment by brunobord** [comment]
hello!

same as for your Kazakhstan PR... just a few lines too long. No big deal, and your PR can be merged right after that.

**Comment by atj01** [comment]
Hi @brunobord, 

many thanks for looking into this PR! Sorry, I totally missed the flak8 tests..  I've checked the failing tests and I fixed the flake8 issues. Hopefully it will pass now all the tests.

**Comment by brunobord** [comment]
same as for the Kazakhstan PR, I'll integrate this patch in a bigger "meta PR"

**Comment by brunobord** [comment]
superseeded by https://github.com/workalendar/workalendar/pull/699

**Comment by brunobord** [comment]
Georgia has been included in the latest release of Workalendar, now available on PyPI!

* https://github.com/workalendar/workalendar/releases/tag/16.3.0
* https://pypi.org/project/workalendar/16.3.0/

**Pull request closed without merging**
