### PR TITLE
Japan calendar update because of the 2021 Olympics

### PR DESCRIPTION
**Pull request by brunobord**
refs #662 / superseeds and thus closes #663

- [x] Tests with a significant number of years to be tested for your calendar.
- [x] Changelog amended with a mention describing your changes. **Note** *Please do NOT change the version number here. It's the project maintainers' duty.*
- [x] Rebase / Squash

### CODE REVIEW

**Comment by brunobord** [comment]
could you please review this branch, @lxlgarnett?

**Comment by lxlgarnett** [comment]
> could you please review this branch, @lxlgarnett?

Yes, it's looks good to me. Thank you.

**Comment by brunobord** [comment]
Ok, so I'm going to merge this PR as soon as its tests will be green... but I'm sorry, but you'll have to wait a bit for a release. It's almost midnight here, and I prefer to make the release when I'll have some sleep.
But this release is my highest priority, since it may impact Japanese users immediatly.

**Comment by lxlgarnett** [comment]
> Ok, so I'm going to merge this PR as soon as its tests will be green... but I'm sorry, but you'll have to wait a bit for a release. It's almost midnight here, and I prefer to make the release when I'll have some sleep.
> But this release is my highest priority, since it may impact Japanese users immediatly.

Thank you so much. Have a good night.

**Pull request merged**
