### PR TITLE
Add Coronation of His Majesty King Charles III Bank holiday in 2023 to the UK calendar.

### PR DESCRIPTION
**Pull request by mountinash789**
[GOV.UK Press release](https://www.gov.uk/government/news/bank-holiday-proclaimed-in-honour-of-the-coronation-of-his-majesty-king-charles-iii)

- [x] Tests with a significant number of years to be tested for your calendar.
- [x] Changelog amended with a mention describing your changes. **Note** *Please do NOT change the version number here. It's the project maintainers' duty.*

### CODE REVIEW

**Comment by brunobord** [comment]
could you please rebase your PR from the latest master branch? It has dropped support for Python 3.6, and added support for Python 3.10/3.11

(if you have any trouble rebasing, please tell me)

**Comment by mountinash789** [comment]
@brunobord Happy New Year, I have rebased from master. Tests are failing because of the lack of support for 2023 in the Chinese calendar.

**Comment by brunobord** [comment]
okay, great... and oops, not so great.
There's an ongoing PR here: https://github.com/workalendar/workalendar/pull/728 about China's 2023 holidays.

when it's merged you'll have to (unfortunately) re-rebase against the new master.
sorry about that.

**Comment by brunobord** [comment]
now you can. :o)

**Comment by brunobord** [comment]
ok, bear with me for a minute: I'm going to make a release, and then you'll be able to rebase from latest master.

**Comment by brunobord** [comment]
okay, you're clear to rebase.

Again, sorry for the inconvenience.

**Comment by jaraco** [comment]
I've merged this feature into the [calendra](https://pypi.org/project/calendra) project and released as v7.9.0.

**Pull request merged**
