### PR TITLE
Conditional 2-1/26-12 holidays in Neuchatel

### LINKED ISSUE #697: Missing conditional holidays for Neuchatel (Switzerland)
26.12 and 2.1 are holidays in Canton of Neuchatel only when the preceding day is a Sunday.
References:
- https://fr.wikipedia.org/wiki/Jours_fériés_en_Suisse
- https://www.ne.ch/themes/travail/pages/jours-feries.aspx
- http://rsn.ne.ch/DATA/program/books/rsne/pdf/94102.pdf

### PR DESCRIPTION
**Pull request by claudep**
closes #697

- [x] Tests with a significant number of years to be tested for your calendar.
- [x] Changelog amended with a mention describing your changes. **Note** *Please do NOT change the version number here. It's the project maintainers' duty.*

### CODE REVIEW

**Comment by brunobord** [comment]
There's a massive incoming PR with long-time due contributions. It'll most probably cause merge conflicts. You have several solutions here: either I'll merge de meta-PR and let *you* solve the conflict by rebasing from master ; or I'll integrate your contribution into the meta-PR.
Either way, your contribution won't be forgotten and will be integrated as soon as I can.

What do you think?

**Comment by claudep** [comment]
Hello Bruno, feel free to merge your PR as planned, I'll take care of rebasing after that.

**Comment by brunobord** [comment]
you can rebase from master, now. Have fnu!

**Comment by claudep** [comment]
Easy, bro :-)

**Pull request merged**
