### PR TITLE
Add calendar for Kazakhstan

### PR DESCRIPTION
**Pull request by atj01**
This PR is intended to add a new calendar for the country of Kazakhstan.
 #

For information, read and make sure you're okay with the [Contributing guidelines](https://workalendar.github.io/workalendar/contributing.html#adding-new-calendars).

- [x] Tests with a significant number of years to be tested for your calendar.
- [x] Docstrings for the Calendar class and specific methods.
- [x] Use the ``workalendar.registry_tools.iso_register`` decorator to register your new calendar using ISO codes (optional).
- [x] Calendar country / label added to the README.md file.
- [x] Changelog amended with a mention like: "Added ``<country>`` by ``@pseudo`` (#)". **Note** *Please do NOT change the version number here. It's the project maintainers' duty.*

### CODE REVIEW

**Comment by brunobord** [comment]
your PR looks like it's working. Unfortunately, it didn't pass the flake8 checks.
https://github.com/workalendar/workalendar/runs/4475641623?check_suite_focus=true

Could you please fix these errors? (mostly "lines too long", due to comments — do not hesitate to put your comments above to save place)

You're almost there, don't despair! I'm eagerly waiting for your contribution to be ready!

**Comment by brunobord** [comment]
There's also a Python error in the label assertions. You'll have to make sure that, for the iCal export, each label should be unique. You'll have to check that you don't have the same label twice, then.

**Comment by atj01** [comment]
Hi @brunobord,

Thanks a lot for looking into this PR and your comments are greatly appreciated! I fixed the flake8 issues as well as the multiple labels / dates appearing in case the get_fixed_holidays() method is called multiple times. Sorry that was a stupid mistake in get_fixed_holidays().. I hope this will pass now. Thanks again for checking!

**Comment by brunobord** [comment]
I'm so late with all the current PRs…
I'm going to take your contribution into account, but in a different way than the others! Stay tuned!

**Comment by brunobord** [comment]
Kazakhstan has been included in the latest release of Workalendar, now available on PyPI!

* https://github.com/workalendar/workalendar/releases/tag/16.3.0
* https://pypi.org/project/workalendar/16.3.0/

**Pull request closed without merging**
